name: Triggered every 1hour
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  setUpAndRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      with:
        node-version: 12
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: "**/node_modules"
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install Node.js dependencies
        run: |-
          if [[ "${{ inputs.force_install }}" == "true" || "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]]; then
            npm install
          else
            echo "Using cache"
          fi
        shell: bash
      - name: Run Node.js script
        run: npm start
        env:
          API_KEY: ${{ secrets.BOT_TOKEN }}